version: "3"
services:
  nsqlookupd:
    image: nsqio/nsq 
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - services


  nsqd:
    depends_on:
      - nsqlookupd  
    depends_on:
      - nsqlookupd 
    image: nsqio/nsq 
    ports:
      - "4150:4150"
      - "4151:4151"
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1
    networks:
      - services


  nsqadmin:
    depends_on:
      - nsqlookupd  
    image: nsqio/nsq 
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
      - services


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - services


  backend-base:
    image: backend-base
    networks:
      - services


  frontend-catalog:
    depends_on:
      - backend-catalog-api
    image: frontend-catalog
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - services
  
  
  backend-catalog-api:
    depends_on:
      - backend-base
      - backend-catalog
    image: backend-catalog-api
    ports:
      - "3001:3001"
    networks:
      - services
  
  
  backend-catalog:
    depends_on:
      - backend-base
      - elasticsearch 
      - nsqd
    image: backend-catalog
    networks:
      - services
  
  
  backend-catalog-favorite:
    depends_on:
      - backend-base
    image: backend-catalog-favorite
    networks:
      - services
  
  
  backend-catalog-psn:
    depends_on:
      - backend-base
    image: backend-catalog-psn
    networks:
      - services
  
  
  backend-catalog-xbox:
    depends_on:
      - backend-base
    image: backend-catalog-xbox
    networks:
      - services


  backend-catalog-steam:
    depends_on:
      - backend-base
    image: backend-catalog-steam
    networks:
      - services


networks:
  services:
